config/routes.rb
Heartbeat::Application.routes.draw do

  root :to => "users#index"

  post "update" => "users#update"
  get "get_users" => "users#get_users"

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :id, :beats, :x, :y
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  def get_users
    @users = User.all
    respond_to do |format|
      format.json { render json: @users }
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find_or_create_by_id(params[:id])
    coord = params[:loc].split(',').map{|x| x.to_i}
    @user.x = coord[0]
    @user.y = coord[1]
    @user.beats = params[:beats]
    @user.save
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Heartbeat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :beats %><br />
    <%= f.text_field :beats %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/index.html.erb
<script type="text/javascript">


var audio = new Audio('audio/heartbeat.mp3');
function plot(user){
  div = $("#"+user.id);
  if(div.length==0){
    div = $('<div class="circle"></div>');
    div.attr('id',user.id);
    $("body").append(div);
  }
  div.attr("delay",user.beats);
  div.offset({left:user.x, top:user.y});
}

function pulse(id) {
    delay = parseInt($('#'+id).attr("delay"));
    $('#'+id).animate({
        width: 50, height: 50, 
        opacity: 0.5
    }, delay, function() {
        $('#'+id).animate({
            width: 60, height: 60, 
            opacity: 1
        }, delay, function() {
            audio.play();
            pulse(id);
        });
    }); 
};

$( document ).ready(function() {
     function fetchData() {
     $.ajax({
      url:      '/get_users',
      method:   'GET',
      dataType: 'json',
      success:  function(users) {
          users.forEach(function(user) {
 		 plot(user);
	         pulse(user.id);
	  });
          setTimeout(fetchData,  100);
	}
      });
    }	
    fetchData();  
   
});

</script>

<style type="text/css">
.circle {
	position: absolute;
	border-radius: 50%;
	width: 50px;
	height: 50px; 
	background-image: -moz-radial-gradient(45px 45px 45deg, circle cover, red 0%, orange 100%, yellow 95%);
	background-image: -webkit-radial-gradient(45px 45px, circle cover,red , orange);
	background-image: radial-gradient(45px 45px 45deg, circle cover, red, 0%, orange 100%, yellow 95%);
}

</style>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @user.location %>
</p>

<p>
  <b>Beats:</b>
  <%= @user.beats %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>